server:
  port: 3000

app:  
  social:
   urls:
     twitter: https://takehome.io/twitter
     facebook: https://takehome.io/facebook
     instagram: https://takehome.io/instagram

rest:
  connection.timeout: 2000
  read.timeout: 2000